### ISSUE TITLE
Error what is the reason?

### ISSUE THREAD

**Issue by alexsahka** [twocolors/node-red-contrib-home-assistant-discovery#3]
![image](https://user-images.githubusercontent.com/7469537/193164126-97d3558b-a496-4d70-a2c7-486348310958.png)
![image](https://user-images.githubusercontent.com/7469537/193164310-c5440789-3a68-4f89-9e0c-b512dabc50f2.png)
![image](https://user-images.githubusercontent.com/7469537/193164348-8719ef42-313d-4a68-bdc8-c2e2726b263f.png)

I have this node-red-contrib-ha-mqtt installed
https://flows.nodered.org/node/node-red-contrib-ha-mqtt

and I think this node is causing this error

Here is the Docker Nodered Log:

![image](https://user-images.githubusercontent.com/7469537/193164641-eb3507e7-d75e-4538-8982-e5012c4bed27.png)

**Comment by twocolors** [comment]
try node-red-contrib-home-assistant-discovery@0.0.8

**Comment by alexsahka** [comment]
Could you update  the https://flows.nodered.org/node/node-red-contrib-home-assistant-discovery

**Comment by twocolors** [comment]
@alexsahka update , wait ~ 15min

**Comment by alexsahka** [comment]
![image](https://user-images.githubusercontent.com/7469537/194160157-365c7621-2a65-45bd-b29c-7b3a27573327.png)
Node red is deployed

**Comment by alexsahka** [comment]
Node red is deployed, but no devices.
 MQTT Explorer showing activity under the topic

**Comment by alexsahka** [comment]
Here is the Node red log

![image](https://user-images.githubusercontent.com/7469537/194160921-bd1dd9ee-5d30-4ec8-8e4b-efb228d7b04f.png)

**Comment by alexsahka** [comment]
I'm using ha/# topic instead of homeassistant/#

**Comment by twocolors** [comment]
show screenshots from the settings (ha-discovery) and from mqtt client

**Comment by alexsahka** [comment]
![image](https://user-images.githubusercontent.com/7469537/194163554-4b8655a7-d6f1-4fab-abde-533c194425ad.png)

![image](https://user-images.githubusercontent.com/7469537/194163598-6111c18a-dd95-43db-9632-855f4ae96345.png)

**Comment by twocolors** [comment]
nodejs and node-red version ?

**Comment by alexsahka** [comment]
NodeRed in Docker
![image](https://user-images.githubusercontent.com/7469537/194165126-eec8a88d-6665-4590-bc13-cea6a92be45c.png)

**Comment by twocolors** [comment]
in docker log, like this
```
node-red     | 5 Oct 21:47:07 - [info] Node-RED version: v3.0.2
node-red     | 5 Oct 21:47:07 - [info] Node.js  version: v16.17.0
node-red     | 5 Oct 21:47:07 - [info] Linux 5.15.61-v8+ arm64 LE
node-red     | 5 Oct 21:47:08 - [info] Loading palette nodes
```

**Comment by alexsahka** [comment]
Node-RED version: v3.0.2
Node.js  version: v16.16.0
Linux 4.19.0-14-amd64 x64 LE
Loading palette nodes

**Comment by twocolors** [comment]
can you show me full patch some sensor (ha/sensor/...) and json this sensor and screen?

like
```
homeassistant/sensor/bathroom-fan/temperature/config

{"dev_cla":"temperature","unit_of_meas":"°C","stat_cla":"measurement","name":"Temperature","stat_t":"esphome/bathroom-fan/sensor/temperature/state","avty_t":"esphome/bathroom-fan/status","uniq_id":"ESPsensortemperature","dev":{"ids":"70039f0d06d3","name":"bathroom-fan","sw":"esphome v2022.9.2 Oct  6 2022, 00:31:33","mdl":"esp8285","mf":"espressif"}}
```

<img width="1092" alt="image" src="https://user-images.githubusercontent.com/207796/194221203-50e45ccc-aa31-4dff-99a7-65bd26aa2d21.png">


it's best to get your base completely mqtt

**Comment by alexsahka** [comment]
![image](https://user-images.githubusercontent.com/7469537/194226197-99a404fe-2789-4c33-96dc-89d5541558c7.png)
 There is no json for any of my sensors

**Comment by twocolors** [comment]
oh i thinks this is not HA (MQTT Discovery)

format topic (https://www.home-assistant.io/docs/mqtt/discovery/#discovery-topic)
```
<discovery_prefix>/<component>/[<node_id>/]<object_id>/config
```

and payload must be json [more](https://www.home-assistant.io/docs/mqtt/discovery/#discovery-payload)
